lunararc.launcher.welcome=Welcome to LunarArc Server!
lunararc.launcher.select_modloader=Please select a modloader:
lunararc.launcher.release_name= (Trial Zenith)
lunararc.launcher.logo.0=
lunararc.launcher.logo.1=   §b  _      _   _  _   _    _    ____      _     ____    ____ 
lunararc.launcher.logo.2=   §b | |    | | | || \\ | |  / \\  |  _ \\    / \\   |  _ \\  / ___|
lunararc.launcher.logo.3=   §b | |    | | | ||  \\| | / _ \\ | |_) |  / _ \\  | |_) || |    
lunararc.launcher.logo.4=   §b | |___ | |_| || |\\  |/ ___ \\|  _ <  / ___ \\ |  _ < | |___ 
lunararc.launcher.logo.5=   §b |_____| \\___/ |_| \\_/_/   \\_\\_| \\_\\/_/   \\_\\|_| \\_\\ \\____|
lunararc.launcher.logo.6=
lunararc.launcher.logo.7=    §aVersion %s / %s
lunararc.launcher.logo.8=    §aBuild Date %s
lunararc.launcher.logo.9=
