plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = project(':lunararc-common').file("src/main/resources/lunararc.accesswidener")
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.minecraft.get()}:${libs.versions.parchment.get()}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${libs.versions.fabric.loader.get()}"
    implementation project(':lunararc-common')
    implementation project(':api')
    implementation libs.paper.api
}

processResources {
    inputs.property "version", project.version
    inputs.property "project_name", rootProject.name
    inputs.property "minecraft", libs.versions.minecraft.get()
    inputs.property "fabric_loader", libs.versions.fabric.loader.get()

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                project_name: rootProject.name,
                minecraft: libs.versions.minecraft.get(),
                fabric_loader: libs.versions.fabric.loader.get()
        )
    }
}
