plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    loader("quilt")
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = project(':lunararc-common').file("src/main/resources/lunararc.accesswidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentQuilt.extendsFrom common
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.minecraft.get()}:${libs.versions.parchment.get()}@zip")
    }

    // Quilt Loader
    modImplementation libs.quilt.loader
    modImplementation "net.fabricmc:fabric-loader:${libs.versions.fabric.loader.get()}"

    // Architectury transformation logic
    common(project(path: ":base", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":base", configuration: "transformProductionQuilt")) { transitive false }

    implementation project(':api')
    implementation libs.paper.api
}

processResources {
    inputs.property "version", project.version
    inputs.property "project_name", rootProject.name
    inputs.property "minecraft", libs.versions.minecraft.get()
    inputs.property "quilt_loader", libs.versions.quilt.loader.get()

    filesMatching("quilt.mod.json") {
        expand(
                version: project.version,
                project_name: rootProject.name,
                minecraft: libs.versions.minecraft.get(),
                quilt_loader: libs.versions.quilt.loader.get()
        )
    }
}
