modLoader="javafml"
loaderVersion="[1,)"
license="Apache-3.0"

[[mods]]
modId="lunararc"
version="${version}"
displayName="${project_name}"
authors="Ampz Network"
description="LunarArc Hybrid Server Core"

[[mixins]]
config="mixins.lunararc.common.neoforge.json"
