modLoader="javafml"
loaderVersion="[1,)"
license="Apache-3.0"

[[mods]]
modId="lunararc"
version="${file.jarVersion}"
displayName="LunarArc"
authors="Ampz Network"
description="LunarArc Hybrid Server Core"

[[mixins]]
config="mixins.lunararc.common.json"

[[mixins]]
config="mixins.lunararc.neoforge.json"
