package io.ampznetwork.lunararc.common.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Plugins and mods LunarArc refuses to run, or warns about, compiled into the build.
 *
 * <p>This used to be {@code lunararc-blacklist.yml}, written out on first start for the server
 * operator to edit. That was the wrong shape for what the list is. An entry here is not a
 * preference - it is LunarArc stating that a specific plugin or mod is known to break on it, which
 * is knowledge the project has and the operator does not. A file that ships empty and invites
 * editing puts the burden on the person least able to carry it, and an operator who deleted or
 * corrupted it silently lost every protection in it.</p>
 *
 * <h2>Adding an entry</h2>
 *
 * <p>Edit {@code gradle/blacklist.toml}, beside {@code libs.versions.toml}, and rebuild. That file
 * documents the schema and is the only place entries are written. The build parses it and emits
 * {@code lunararc/blacklist.tsv} into the jar; this class reads that resource and nothing else.</p>
 *
 * <p>A malformed entry fails the build naming the line, rather than being dropped, so an entry
 * someone believes is protecting them always is.</p>
 */
public final class PluginBlacklist {

    private static final Logger LOGGER = LoggerFactory.getLogger("LunarArc");

    /**
     * Bukkit/Spigot/Paper plugins refused at load time.
     *
     * <p>Matched on the name in plugin.yml or paper-plugin.yml, case-insensitively. A plugin
     * listed here is never constructed: the load fails with its reason, in the same way an
     * unsatisfied dependency does.</p>
     */
    private static final List<Entry> PLUGINS;

    /**
     * Mod IDs known to be incompatible.
     *
     * <p>Matched on the loader's mod ID, case-insensitively. Unlike a plugin, a mod is already
     * loaded and running by the time LunarArc can see it - the loader resolved and constructed it
     * long before any of our code runs - so this cannot refuse one. It warns, loudly and by name,
     * which is the honest limit of what is possible here and is still worth having: it turns "the
     * server behaves strangely" into a line naming the cause.</p>
     */
    private static final List<Entry> MODS;

    static {
        List<Entry> plugins = new ArrayList<>();
        List<Entry> mods = new ArrayList<>();
        // Generated by the generateBlacklist Gradle task from gradle/blacklist.toml. Absent only
        // in a build that skipped resource generation; an empty list is the right answer there,
        // since the alternative is refusing to start over a list that is empty by construction.
        try (InputStream stream = PluginBlacklist.class.getClassLoader()
                .getResourceAsStream("lunararc/blacklist.tsv")) {
            if (stream != null) {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(stream, StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        if (line.isBlank()) continue;
                        // section \t name \t version \t reason; the build guarantees the shape,
                        // and reason is last so it may contain anything but a tab.
                        String[] parts = line.split("\t", 4);
                        if (parts.length < 4) continue;
                        Entry entry = new Entry(parts[1], parts[2].isEmpty() ? null : parts[2], parts[3]);
                        if ("mods".equals(parts[0])) {
                            mods.add(entry);
                        } else {
                            plugins.add(entry);
                        }
                    }
                }
            }
        } catch (IOException failure) {
            LOGGER.error("Could not read the built-in incompatibility list; nothing will be blocked", failure);
        }
        PLUGINS = List.copyOf(plugins);
        MODS = List.copyOf(mods);
    }

    private PluginBlacklist() {
    }

    /**
     * The entry blocking a plugin, or {@code null} if it is allowed.
     *
     * @param pluginName    name from the plugin descriptor
     * @param pluginVersion version from the plugin descriptor
     */
    public static Entry check(String pluginName, String pluginVersion) {
        return find(PLUGINS, pluginName, pluginVersion);
    }

    /**
     * The entry naming a mod as incompatible, or {@code null} if it is not listed.
     *
     * @param modId   the loader's mod ID
     * @param version the mod's version, or {@code null} if the loader does not report one
     */
    public static Entry checkMod(String modId, String version) {
        return find(MODS, modId, version);
    }

    /**
     * Warn about any loaded mod that is listed, once, at startup.
     *
     * <p>Called by each loader module with the mods that loader resolved, since only the loader
     * can enumerate them.</p>
     *
     * @param loadedMods mod ID to version; a null version matches an entry with no version pinned
     */
    public static void screenLoadedMods(Map<String, String> loadedMods) {
        if (MODS.isEmpty() || loadedMods == null || loadedMods.isEmpty()) return;
        for (Map.Entry<String, String> mod : loadedMods.entrySet()) {
            Entry listed = checkMod(mod.getKey(), mod.getValue());
            if (listed == null) continue;
            LOGGER.warn("Mod '{}'{} is known to be incompatible with LunarArc: {}",
                    mod.getKey(),
                    mod.getValue() == null ? "" : " " + mod.getValue(),
                    listed.reason());
            LOGGER.warn("It is already loaded and cannot be stopped from here. Remove it from the "
                    + "mods folder if the server misbehaves.");
        }
    }

    private static Entry find(List<Entry> entries, String name, String version) {
        if (name == null) return null;
        for (Entry entry : entries) {
            if (!entry.name().equalsIgnoreCase(name)) continue;
            if (entry.version() == null || entry.version().equals(version)) return entry;
        }
        return null;
    }

    /**
     * One blocked plugin or mod.
     *
     * @param name    plugin name or mod ID, matched case-insensitively
     * @param version exact version to match, or {@code null} for every version
     * @param reason  shown to the operator verbatim
     */
    public record Entry(String name, String version, String reason) {
    }
}
