
plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = project(':lunararc-common').file('src/main/resources/lunararc.accesswidener')
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.minecraft.get()}:${libs.versions.parchment.get()}@zip")
    }
    neoForge libs.neoforge
    implementation project(':lunararc-common')
    implementation project(':lunararc-api')
    implementation libs.paper.api
}

tasks.named('jar') {
    exclude 'net/neoforged/neoforgespi/**'
}

processResources {
    def javaRuntime = libs.versions.java.runtime.get()
    inputs.property 'version', project.version
    inputs.property 'project_name', rootProject.name
    inputs.property 'java_runtime', javaRuntime

    filesMatching('META-INF/mods.toml') {
        expand version: project.version, project_name: rootProject.name
    }
    filesMatching('mixins.lunararc.neoforge.json') {
        expand java_compatibility: "JAVA_${javaRuntime}"
    }
}
