projectName=${project_name}
version=${version}
buildName=${buildName}
minecraft=${minecraft}
javaVersion=${javaRuntime}
paperApi=${paperApi}
paperBuild=${paperBuild}
dataVersion=${dataVersion}
neoforge=${neoforge}
forge=${forge}
fabric=${fabric}
quilt=${quilt}
